-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users Table
create table public.users (
  user_id bigint generated by default as identity primary key,
  full_name text not null,
  email text unique not null,
  password_hash text not null,
  phone_number text,
  date_of_birth timestamp with time zone,
  bio text,
  profile_picture_path text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_login timestamp with time zone,
  biometric_enabled boolean default false,
  pin_code text,
  theme_preference text default 'auto',
  language_preference text default 'en',
  is_active boolean default true
);

-- Categories Table
create table public.categories (
  category_id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id) on delete cascade not null,
  category_name text not null,
  category_color text default '#8B5CF6',
  category_icon text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_deleted boolean default false
);

-- Tasks Table
create table public.tasks (
  task_id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id) on delete cascade not null,
  title text not null,
  description text,
  priority integer default 3 check (priority >= 1 and priority <= 5),
  category_id bigint references public.categories(category_id) on delete set null,
  status text default 'active' check (status in ('active', 'completed', 'archived')),
  due_date timestamp with time zone,
  reminder_time timestamp with time zone,
  reminder_type text,
  is_recurring boolean default false,
  recurrence_pattern text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  completed_at timestamp with time zone,
  is_deleted boolean default false
);

-- Task Images Table
create table public.task_images (
  image_id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(task_id) on delete cascade not null,
  image_path text not null,
  image_caption text,
  upload_date timestamp with time zone default timezone('utc'::text, now()) not null,
  image_order integer default 0
);

-- Subtasks Table
create table public.subtasks (
  subtask_id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(task_id) on delete cascade not null,
  subtask_title text not null,
  is_completed boolean default false,
  subtask_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  completed_at timestamp with time zone
);

-- Tags Table
create table public.tags (
  tag_id bigint generated by default as identity primary key,
  tag_name text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Task Tags Junction Table
create table public.task_tags (
  task_tag_id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(task_id) on delete cascade not null,
  tag_id bigint references public.tags(tag_id) on delete cascade not null,
  unique(task_id, tag_id)
);

-- Notifications Table
create table public.notifications (
  notification_id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id) on delete cascade not null,
  notification_type text not null,
  title text not null,
  message text,
  related_task_id bigint references public.tasks(task_id) on delete cascade,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Task Activity Log Table
create table public.task_activity_log (
  log_id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(task_id) on delete cascade,
  user_id bigint references public.users(user_id) on delete cascade not null,
  action_type text not null,
  action_description text,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- App Settings Table
create table public.app_settings (
  setting_id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id) on delete cascade not null,
  setting_key text not null,
  setting_value text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, setting_key)
);

-- Backup Metadata Table
create table public.backup_metadata (
  backup_id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id) on delete cascade not null,
  backup_path text not null,
  backup_size integer,
  backup_date timestamp with time zone default timezone('utc'::text, now()) not null
);

-- User Statistics Table
create table public.user_statistics (
  stat_id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id) on delete cascade not null,
  date date not null,
  tasks_created integer default 0,
  tasks_completed integer default 0,
  tasks_overdue integer default 0,
  productivity_score double precision default 0,
  unique(user_id, date)
);

-- Indexes
create index idx_tasks_user_id on public.tasks(user_id);
create index idx_tasks_status on public.tasks(status);
create index idx_tasks_due_date on public.tasks(due_date);
create index idx_tasks_category_id on public.tasks(category_id);
create index idx_categories_user_id on public.categories(user_id);
create index idx_notifications_user_id on public.notifications(user_id);
create index idx_notifications_read on public.notifications(is_read);
create index idx_task_activity_task_id on public.task_activity_log(task_id);
create index idx_user_statistics_user_date on public.user_statistics(user_id, date);

-- Row Level Security (RLS) Policies (Optional but recommended for Supabase)
-- Enabling RLS on users table
alter table public.users enable row level security;

-- Policy to allow users to see only their own data (This implies you use Supabase Auth and map user_id to auth.uid())
-- Since we are using an integer user_id and not Supabase's UUID auth.uid() directly in this schema (as it mirrors the SQLite schema),
-- we would need a mapping or just trust the application logic if this is a standalone backend replacement.
-- For a true Supabase integration, user_id should ideally be uuid references auth.users.
-- However, to match the Flutter app's current 'int' ID expectations, we keep it as bigint for now.

